In [1]:
import torch as t
from collections import Counter
import torchtext

In [2]:
t.manual_seed(0)

# 1) Tensors in detail

In [3]:
''' Argmax is cool, simply gets the indices of highest values.
    1 - Vertical/Row by row.
    0 - Horizontal/Column by column.

    So:
    1 - Indices 1,0,1,2 and the numbers are 7,10,5,22.
    0 - Indices 1,3,3 and the numbers are 10,20,22.

    Argmin is opposite. '''

z = t.tensor([[3, 7, 1],
              [10, 3, 5],
              [4, 5, 1],
              [4, 20, 22]])

print(f'---Argmax---')
print(t.argmax(z, 1))
print(t.argmax(z, 0))
print('\n\n')

print(f'---Argmin---')
print(t.argmin(z, 1))
print(t.argmin(z, 0))

---Argmax---
tensor([1, 0, 1, 2])
tensor([1, 3, 3])



---Argmin---
tensor([2, 1, 2, 0])
tensor([0, 1, 0])


In [4]:
''' view/reshape very similar

   Both inputs are row/column
   Format. Can give -1 to one
   Arg to say "figure out this
   Dimension"
'''

x = t.tensor([5,6,7,8])

print(x.reshape(2,2))
print(x.view(2,2))

tensor([[5, 6],
        [7, 8]])
tensor([[5, 6],
        [7, 8]])


In [5]:
''' Seems to get a certain
amount of values from given ts,
and if replacement if True,
can get more values.
'''
x = t.tensor([4,2,5,7],
              dtype=t.float32)

t.multinomial(x, 4)

tensor([2, 3, 1, 0])

In [6]:
# same with zeros
# a = t.ones(5)
a = t.ones(5, 2) # 2d. 5 rows 2 colunns
# a = t.ones(2, 2, 4) #3d. 2 rows 4 columns

a

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [7]:
''' bt = basic tensor
Can change dtype and device
If necessary
'''
bt = t.tensor([5, 4, 7],
              dtype=t.float32)

bt

tensor([5., 4., 7.])

In [8]:
# 2d
bt = t.tensor(
   [[1,3,5],
    [7,8,9]]
)

print(bt)
print(bt.shape)

tensor([[1, 3, 5],
        [7, 8, 9]])
torch.Size([2, 3])


### 1.2) Indexing

In [9]:
# indexing

# bt[0] # get row. Gets element in 1d tensor
# bt[1,2] # get 9
bt[1][2]

tensor(9)

### 1.3) One hot encoding with tensors

In [10]:
import torch.nn.functional as f

''' "Used to indicate the presence
of a value and lack of presence
of other values."

Below goes in order in each
Tensor. Like index 0,1,2,3,4,5
Will be indicative of the slot
For each num. Hence why 5s tensor
Gets ITS 1 at end. '''

l = t.tensor([5,1,0,1,0])
f.one_hot(l, num_classes=6)

tensor([[0, 0, 0, 0, 0, 1],
        [0, 1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0]])

### 1.3) Slicing, dtype, & typecast

In [11]:
import numpy as np

# Slicing

X = t.tensor([5,4,1,8,9])

# X[:] # all elements
# X[1:3] # gets 4,1
# X[:2] # gets 5,4

# bt[0,:] # get first row
# bt[:,0] # get first column
# bt[...,0] # get first column

# X.dtype # type check. Comes in useful a lot tbh
# t.tensor([4,3,2], dtype=t.float32) # Create tensors of a certain type.
# X.numpy() # typecast

h = np.array([[8,7,6,5],[4,3,2,1]])
ht = t.from_numpy(h) # array to ts
ht

tensor([[8, 7, 6, 5],
        [4, 3, 2, 1]])

In [12]:
t.tensor([4,3,2], dtype=t.float32)

tensor([4., 3., 2.])

In [13]:
# tensor to Numpy and Numpy to tensor

x = np.array([1,3,5,7])

# to tensor
print(f'x:\n{x}\ntype: {type(x)}\n')
x = t.tensor(x)
print(f'x:\n{x}\ntype: {type(x)}\n')

# to numpy arr
Y = x.numpy()
print(f'Y:\n{Y}\ntype: {type(Y)}\n')

x:
[1 3 5 7]
type: <class 'numpy.ndarray'>

x:
tensor([1, 3, 5, 7])
type: <class 'torch.Tensor'>

Y:
[1 3 5 7]
type: <class 'numpy.ndarray'>



### 2) Math & Etc

In [14]:
# change in tensor changes np arr
print(x.add_(1))
print(Y)

tensor([2, 4, 6, 8])
[2 4 6 8]


In [15]:
# math

Y = t.tensor([1,2,3,4,5])

# basic tensor math can be done below
# X + Y # add
# t.add(X, Y) # add


# Y - Y # sub
# t.sub(Y, Y) # sub

# Y * 2 # scalar multiplication. Multiples elements by 2
# Y * Y # tensor & tensor multiplication

# Y / Y # division


# Y / 2 # Scalar division.
# t.divide(Y, Y) # Scalar division.
Y / Y # more scalar division

tensor([1., 1., 1., 1., 1.])

In [16]:
''' cumsum - Goes throughout a tensor
    and just adds things

    1) Ex 1d tensor, dim 0 -
    The following explanation has been copied from
    a previous Google Colab I have and slightly
    edited:

    "cumsum (when dim=0), takes the groups of the numbers in the tensor to make a
    NEW tensor.
    Ex: If vector is [1,2,3,4], then cumsum creates new vector.
      1) 1 is first group, it's added to vector to make [1]
      2) 1,2 is second group, all are added and assigned to vector to make [1,3]
      3) 1,2,3 is third group, all are added and assigned to vector to make [1,3,6]
      4) 1,2,3,4 is fourth group, all are added and assigned to vector to make [1,3,6,10]"

    2) Ex 1d tensor, dim 1 -
      Doesn't work, the error "IndexError: Dimension out of range (expected to be
      in range of [-1, 0], but got 1)" came because 1 indicates going vertically.

    3) Ex 2d tensor, dim 0 -
      Like below example, if dim is 0, it goes column to column. So 1+4=5, that'll
      be the first number in the second tensor. 2+5=7, place THAT in the next
      index of the second tensor, etc.

    4) Ex 2d tensor, dim 1 -
      Works but does the math row by row. Each row, it applies the math described in
      the earlier comment I copied from my other Colab in section 1 above.


'''

c = t.tensor([3,2,5,1,9,5,8]) # Total 33
d = t.tensor([[1,2,3],
              [4,5,6]])

print(t.cumsum(c, dim=0)) # Prints tensor([ 3,  5, 10, 11, 20, 25, 33])
print(t.cumsum(d, dim=1))
print(t.cumsum(d, dim=0))

tensor([ 3,  5, 10, 11, 20, 25, 33])
tensor([[ 1,  3,  6],
        [ 4,  9, 15]])
tensor([[1, 2, 3],
        [5, 7, 9]])


In [17]:
''' Each row of first is
Individually multipled with
Each column. So 2*4, 1*4, 1*4
is 16 '''

a = t.Tensor(
[
    [2, 1, 1],
    [2, 2, 2],
    [3, 5, 3]
])

b = t.Tensor(
[
    [4, 5, 7],
    [4, 5, 7],
    [4, 5, 7]
])

c = t.mm(a, b)

c

tensor([[16., 20., 28.],
        [24., 30., 42.],
        [44., 55., 77.]])

In [18]:
''' mean/max/min. Simple. Mean
Will get all elements, div by
Number of elements and return that
Value

1) Mean(1)
Row by row.
Add first row for 64, divide by
Total which is 3, get 21.3
Same for the other rows

2) Mean(0)
Column by column
Add first column for 84, divide by
Total which is 3, get 28
Same for other columns


'''


print(c.type(t.float32))

print(c.mean())
print(c.mean(0))
print(c.mean(1))

tensor([[16., 20., 28.],
        [24., 30., 42.],
        [44., 55., 77.]])
tensor(37.3333)
tensor([28., 35., 49.])
tensor([21.3333, 32.0000, 58.6667])


In [19]:
# c.min() # get min in whole tensor. Same concept for .max()
c[1].min() # get min in specific row

tensor(24.)

In [20]:
# ones/rand_like gets us tensor of same shape

print(c)
print('\n')
print(t.ones_like(c))

tensor([[16., 20., 28.],
        [24., 30., 42.],
        [44., 55., 77.]])


tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [21]:
# t.rand(3) # 1d random nums
t.rand(2,3) # 2d

tensor([[0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901]])

In [22]:
c[:, 1]

tensor([20., 30., 55.])

In [23]:
# change values of column
print(f'c:\n{c}\n')

c[:,1] = 5 # all first column to 5

c

c:
tensor([[16., 20., 28.],
        [24., 30., 42.],
        [44., 55., 77.]])



tensor([[16.,  5., 28.],
        [24.,  5., 42.],
        [44.,  5., 77.]])

In [24]:
x = c[0]
y = c[1]

# t.cat((x,y), dim=0) # combines 1d

# 2d tensor, Dim 1? Puts tensors next to each other
t.cat([c, c], dim=1)

# 2d tensor, dim 0? Stacks tensors on top
# t.cat([c, c], dim=0)

tensor([[16.,  5., 28., 16.,  5., 28.],
        [24.,  5., 42., 24.,  5., 42.],
        [44.,  5., 77., 44.,  5., 77.]])

In [25]:
''' Want to combine tensors? Stack helps. MUST be same dimensions. dim=1 gives vertical alignment, dim=0 gives horizontal.  '''
first_tensor = t.tensor([1,2,3])
second_tensor = t.tensor([5,5,5])

v_tensor = t.stack([first_tensor, second_tensor],dim=1)
h_tensor = t.stack([first_tensor, second_tensor],dim=0)

print(f'Vertical tensor:\n{v_tensor}\n\nHorizontal tensor:\n{h_tensor}\n')
print(f'Vertical tensor shape: {v_tensor.shape}\nHorizontal tensor shape: {h_tensor.shape}')

Vertical tensor:
tensor([[1, 5],
        [2, 5],
        [3, 5]])

Horizontal tensor:
tensor([[1, 2, 3],
        [5, 5, 5]])

Vertical tensor shape: torch.Size([3, 2])
Horizontal tensor shape: torch.Size([2, 3])


In [26]:
# transpose flips dimensions

b = t.tensor([[1., 2., 3.],
              [4., 5., 6.]])

a = t.tensor([5,7,3])

# a.t() # no effect, probably because 1d
b.t() # shape from 2,3 to 3,2

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])

In [27]:

# .add/sub/etc great for in place math
print(f"{b}\n")
b.add_(4)
print(b)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

tensor([[ 5.,  6.,  7.],
        [ 8.,  9., 10.]])


In [28]:
# move tensor to GPU or CPU
# c = c.to(device="cpu")

c

tensor([[16.,  5., 28.],
        [24.,  5., 42.],
        [44.,  5., 77.]])

In [29]:
x = t.tensor([4,5,6,7,8])
y = t.tensor([[4],
              [1],
              [2],
              [7],
              [3]])
print(x.shape)
print(y.shape)
# print(y.T.shape)

''' quick note: x is shape 5
And y is 5,1. 5 rows and 1 column
Since the rows of the 2d tensor
Match the original size/shape
Of 1d tensor, it works.

If I try and transpose y, I get
"tensor([[4, 1, 2, 7, 3]])" and
THAT shape is 1,5. So the rows of
This one won't match the
Original size/shape, so that's why
"t.matmul(x,y.T)" fails
'''
print(t.matmul(x, y))

torch.Size([5])
torch.Size([5, 1])
tensor([106])


In [30]:
# .size is literally like shape. Below is 2 rows, 4 columns.
x = t.tensor([[5,4,3,4],
              [1,7,8,9]])

print(f'Size: {x.size()}\nGet rows: {x.size()[0]}\nGet columns: {x.size()[1]}\n')

print(f'Shape: {x.shape}\nShape rows: {x.shape[0]}\nShape columns: {x.shape[1]}')

Size: torch.Size([2, 4])
Get rows: 2
Get columns: 4

Shape: torch.Size([2, 4])
Shape rows: 2
Shape columns: 4


In [31]:
''' Right now I have no clue
where Id use this. Gives
2d tensor of course '''

t.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [32]:
''' somewhat similar to eye
But here:
1) input MUST be a tensor
2) supports only 1d or 2d.
No 0d, so can't give t.tensor(3)
MUST be t.tensor([3])
'''
x = t.diag(t.tensor([1,2,3]))

In [33]:
# numel gets total num of elements in tensor. 1d, 2d, etc

a = t.ones(4)
print(a.numel())

b = t.zeros(3,5) # 3 rows by 5 columns. Total 15
print(b.numel())

4
15


# 11) Etc

In [34]:
# torch.round

t.manual_seed(0)

x = t.rand(5, dtype=t.float32)

print(f'Random nums:\n{x}\nROUNDED random nums{t.round(x)}\n\n')

# fd = first decimal, sd = second decimal.
fd = t.round(x, decimals=1)
sd = t.round(x, decimals=2)
print(f'Rounded to 1st decimal:\n{fd}\nRounded to 2nd decimal: {sd}')

Random nums:
tensor([0.4963, 0.7682, 0.0885, 0.1320, 0.3074])
ROUNDED random numstensor([0., 1., 0., 0., 0.])


Rounded to 1st decimal:
tensor([0.5000, 0.8000, 0.1000, 0.1000, 0.3000])
Rounded to 2nd decimal: tensor([0.5000, 0.7700, 0.0900, 0.1300, 0.3100])


In [35]:
''' The == compares tensors if they match. Below example, only index 3 doesn't match,
    out of 5 total. That's why with "preds == gts" gets:
    "tensor([ True,  True, False,  True,  True])"

    (preds == gts).float() - just turns bools into Floats,

    then normally . sum is used to get total correct

    This is a good and simple way to calculate accuracy
'''
preds = t.tensor([1,0,1,1,1])
gts = t.tensor([1,0,0,1,1])

# print(preds == gts) # tensor([ True,  True, False,  True,  True])
# print((preds == gts).float()) # tensor([1., 1., 0., 1., 1.])
# print((preds == gts).float().sum())
acc = (preds == gts).float().sum() / len(gts)
acc

tensor(0.8000)

In [36]:

''' unsqueeze literally gives
Another dimension to a tensor.

For a 1d tensor, it's shape can
Go from 4 to 1,4. So now it's in
A row.

unsqueeze(0) Goes from:
"tensor([4, 2, 5, 7])"
To: "tensor([[4, 2, 5, 7]])"
Shape is 1,4

unsqueeze(1) gives each element
Its own row. It's shape is 4,1

'''
x = t.tensor([4,2,5,7])
print(x.shape)
print(x)
print('\n')

y = x.unsqueeze(0)
print(y.shape)
print(y)
print('\n')

z = x.unsqueeze(1)
print(z.shape)
print(z)

torch.Size([4])
tensor([4, 2, 5, 7])


torch.Size([1, 4])
tensor([[4, 2, 5, 7]])


torch.Size([4, 1])
tensor([[4],
        [2],
        [5],
        [7]])


In [37]:
''' For 2d? Below default shape
Is 2,4.
1) unsqueeze(0) makes it go to
3d with shape now is:
"torch.Size([1, 2, 4])"

2) unsqueeze(1) makes it go to
3d as well but with shape
"torch.Size([2, 1, 4])"

'''

y = t.tensor([[2,4,5,7],
              [9,6,3,1]])

print(f'Default tensor:\n{y}\n')

print(y.unsqueeze(0))
print(y.unsqueeze(0).shape)
print('\n')

print(y.unsqueeze(1))
print(y.unsqueeze(1).shape)

Default tensor:
tensor([[2, 4, 5, 7],
        [9, 6, 3, 1]])

tensor([[[2, 4, 5, 7],
         [9, 6, 3, 1]]])
torch.Size([1, 2, 4])


tensor([[[2, 4, 5, 7]],

        [[9, 6, 3, 1]]])
torch.Size([2, 1, 4])


In [38]:
''' squeeze makes us get rid of
a dimension. Shape below is 1,3
After squeeze it goes to 1d so
Shape is 3
'''
a = t.tensor([[3,5,7]])
print(a.shape)

a = a.squeeze()
a.shape

torch.Size([1, 3])


torch.Size([3])

In [39]:
''' get a 2d tensor of random
Values. Squeeze here, whether
Given 1, 0 or nothing, doesn't
Change anything.
'''

t.manual_seed(0)

x = t.rand(3,2)

print(x)
print(x.squeeze())

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320],
        [0.3074, 0.6341]])
tensor([[0.4963, 0.7682],
        [0.0885, 0.1320],
        [0.3074, 0.6341]])


In [40]:
''' 4d tensors. Not exactly applicable to
Nlp programmers since we mainly
Work with but still good to go
Over.

The code creates 3 sets of 3d tensors
Of shape 2,3,3.
2 is how many of the 3,3 tensors to make
3,3 are height and width.

'''
t.manual_seed(0)

r = t.randn((3, 2, 3, 3))


print(f'r shape: {r.shape}\nr:\n{r}\n\n')

print(f'Index 0/1/2 shape: {r[0].shape}')
print(f'Index 0:\n{r[0]}')

r shape: torch.Size([3, 2, 3, 3])
r:
tensor([[[[-1.1258, -1.1524, -0.2506],
          [-0.4339,  0.8487,  0.6920],
          [-0.3160, -2.1152,  0.3223]],

         [[-1.2633,  0.3500,  0.3081],
          [ 0.1198,  1.2377,  1.1168],
          [-0.2473, -1.3527, -1.6959]]],


        [[[ 0.5667,  0.7935,  0.5988],
          [-1.5551, -0.3414,  1.8530],
          [ 0.7502, -0.5855, -0.1734]],

         [[ 0.1835,  1.3894,  1.5863],
          [ 0.9463, -0.8437, -0.6136],
          [ 0.0316, -0.4927,  0.2484]]],


        [[[ 0.4397,  0.1124,  0.5433],
          [-0.3952,  0.2055, -0.4503],
          [-0.5731, -0.5554,  0.5943]],

         [[ 1.5419,  1.8197, -0.5515],
          [-1.3253,  0.1886, -0.0691],
          [-0.4949, -1.4959, -0.1938]]]])


Index 0/1/2 shape: torch.Size([2, 3, 3])
Index 0:
tensor([[[-1.1258, -1.1524, -0.2506],
         [-0.4339,  0.8487,  0.6920],
         [-0.3160, -2.1152,  0.3223]],

        [[-1.2633,  0.3500,  0.3081],
         [ 0.1198,  1.2377,  1.1168],


In [41]:
''' arange is a small but useful
Func for loops and more

1) 0 to 8 by 2s
2) up to 10
3) even uses negative numbers

'''

print(t.arange(0,8,2))
print(t.arange(10))
print(t.arange(-10,0))

tensor([0, 2, 4, 6])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1])


In [42]:
# scalars are just tensors with one value
d = t.tensor(55)

d

tensor(55)

In [43]:

''' Flatten can take a 2d, 3d,
Etc tensor and make it 1d.

Example 1) x is 2d. Total 8
Values since 2 rows * 4 columns is
8. That's why flatten shape is 8
Afterwards

Example 2) 3d. 2 sets of ones
That are 3,3. So 9 total. 9*2
Is 18. So flatten shape is 18.

'''

x = t.tensor([[5,7,9,3],
              [1,2,5,7]])

y = t.ones(2,3,3)

print(x.flatten())
print(x.flatten().shape)
print('\n')

print(y)
print('\n')
print(y.flatten())
print(y.flatten().shape)

tensor([5, 7, 9, 3, 1, 2, 5, 7])
torch.Size([8])


tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])


tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
torch.Size([18])
